### ISSUE TITLE
Log job session

### ISSUE THREAD

**Issue by johansolbakken** [johansolbakken/jobclock#1]
# Todo
- [x] Create a file in persistant storage for storing multiple sessions in a log.
- [x] When ending a job session add that session to the log
- [x] Add subcommand: jobclock log [entry]

Need to be clever with naming the entries.
